[package]
name = "mhandle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dev-dependencies]
futures = "0.3.3"
anyhow = "1.0"
async-std = { version = "1.12", features = ["attributes"] }